// Code generated by mockery v2.14.1. DO NOT EDIT.

package news

import (
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}



type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// NotifyNews provides a mock function with given fields: _a0
func (_m *ServiceMock) NotifyNews(_a0 News) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(News) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_NotifyNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyNews'
type Service_NotifyNews_Call struct {
	*mock.Call
}

// NotifyNews is a helper method to define mock.On call
//  - _a0 news.News
func (_e *Service_Expecter) NotifyNews(_a0 interface{}) *Service_NotifyNews_Call {
	return &Service_NotifyNews_Call{Call: _e.mock.On("NotifyNews", _a0)}
}

func (_c *Service_NotifyNews_Call) Run(run func(_a0 News)) *Service_NotifyNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(News))
	})
	return _c
}

func (_c *Service_NotifyNews_Call) Return(_a0 error) *Service_NotifyNews_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceMock(t mockConstructorTestingTNewService) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
